//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 02:22:44 PM ICT 
//


package com.example.jaxb.domain.pain_001_001_05;

import java.util.ArrayList;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.example.jaxb.util.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for CustomerCreditTransferInitiationV05 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerCreditTransferInitiationV05"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GrpHdr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}GroupHeader48"/&gt;
 *         &lt;element name="PmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}PaymentInstruction9" maxOccurs="unbounded"/&gt;
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}SupplementaryData1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerCreditTransferInitiationV05", propOrder = {
    "groupHeader",
    "paymentInstructions",
    "supplementaryDatas"
})
public class CustomerCreditTransferInitiationV05 implements ToString2
{

    @XmlElement(name = "GrpHdr", required = true)
    @NotNull
    @Valid
    protected GroupHeader48 groupHeader;
    @XmlElement(name = "PmtInf", required = true)
    @NotNull
    @Size(min = 1)
    @Valid
    protected List<PaymentInstruction9> paymentInstructions;
    @XmlElement(name = "SplmtryData")
    @Valid
    protected List<SupplementaryData1> supplementaryDatas;

    /**
     * Gets the value of the groupHeader property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader48 }
     *     
     */
    public GroupHeader48 getGroupHeader() {
        return groupHeader;
    }

    /**
     * Sets the value of the groupHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader48 }
     *     
     */
    public void setGroupHeader(GroupHeader48 value) {
        this.groupHeader = value;
    }

    /**
     * Gets the value of the paymentInstructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentInstructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentInstruction9 }
     * 
     * 
     */
    public List<PaymentInstruction9> getPaymentInstructions() {
        if (paymentInstructions == null) {
            paymentInstructions = new ArrayList<PaymentInstruction9>();
        }
        return this.paymentInstructions;
    }

    /**
     * Gets the value of the supplementaryDatas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplementaryDatas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplementaryDatas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementaryData1 }
     * 
     * 
     */
    public List<SupplementaryData1> getSupplementaryDatas() {
        if (supplementaryDatas == null) {
            supplementaryDatas = new ArrayList<SupplementaryData1>();
        }
        return this.supplementaryDatas;
    }

    public void setPaymentInstructions(List<PaymentInstruction9> value) {
        this.paymentInstructions = value;
    }

    public void setSupplementaryDatas(List<SupplementaryData1> value) {
        this.supplementaryDatas = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = new JAXBToStringStrategy();
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            GroupHeader48 theGroupHeader;
            theGroupHeader = this.getGroupHeader();
            strategy.appendField(locator, this, "groupHeader", buffer, theGroupHeader, (this.groupHeader!= null));
        }
        {
            List<PaymentInstruction9> thePaymentInstructions;
            thePaymentInstructions = (((this.paymentInstructions!= null)&&(!this.paymentInstructions.isEmpty()))?this.getPaymentInstructions():null);
            strategy.appendField(locator, this, "paymentInstructions", buffer, thePaymentInstructions, ((this.paymentInstructions!= null)&&(!this.paymentInstructions.isEmpty())));
        }
        {
            List<SupplementaryData1> theSupplementaryDatas;
            theSupplementaryDatas = (((this.supplementaryDatas!= null)&&(!this.supplementaryDatas.isEmpty()))?this.getSupplementaryDatas():null);
            strategy.appendField(locator, this, "supplementaryDatas", buffer, theSupplementaryDatas, ((this.supplementaryDatas!= null)&&(!this.supplementaryDatas.isEmpty())));
        }
        return buffer;
    }

}
