//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 09:05:05 PM ICT 
//


package com.example.jaxb.domain.pain_001_001_05;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CstmrCdtTrfInitn" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}CustomerCreditTransferInitiationV05"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "customerCreditTransferInitiation"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "CstmrCdtTrfInitn", required = true)
    @NotNull
    @Valid
    protected CustomerCreditTransferInitiationV05 customerCreditTransferInitiation;

    /**
     * Gets the value of the customerCreditTransferInitiation property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerCreditTransferInitiationV05 }
     *     
     */
    public CustomerCreditTransferInitiationV05 getCustomerCreditTransferInitiation() {
        return customerCreditTransferInitiation;
    }

    /**
     * Sets the value of the customerCreditTransferInitiation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerCreditTransferInitiationV05 }
     *     
     */
    public void setCustomerCreditTransferInitiation(CustomerCreditTransferInitiationV05 value) {
        this.customerCreditTransferInitiation = value;
    }

}
