//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 02:22:44 PM ICT 
//


package com.example.jaxb.domain.pain_001_001_05;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.example.jaxb.util.JAXBDateTimeAdapter;
import com.example.jaxb.util.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for GroupHeader48 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupHeader48"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgId" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}Max35Text"/&gt;
 *         &lt;element name="CreDtTm" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}ISODateTime"/&gt;
 *         &lt;element name="Authstn" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}Authorisation1Choice" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="NbOfTxs" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}Max15NumericText"/&gt;
 *         &lt;element name="CtrlSum" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}DecimalNumber" minOccurs="0"/&gt;
 *         &lt;element name="InitgPty" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}PartyIdentification43"/&gt;
 *         &lt;element name="FwdgAgt" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.05}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupHeader48", propOrder = {
    "messageId",
    "createDateTime",
    "authorisationChoices",
    "transactionNumber",
    "ctrlSum",
    "partyIdentification",
    "branchAndFinancialInstitutionIdentification"
})
public class GroupHeader48 implements ToString2
{

    @XmlElement(name = "MsgId", required = true)
    @NotNull
    @Size(min = 1, max = 35)
    protected String messageId;
    @XmlElement(name = "CreDtTm", required = true, type = String.class)
    @XmlJavaTypeAdapter(JAXBDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    @NotNull
    protected Date createDateTime;
    @XmlElement(name = "Authstn")
    @Size(min = 0, max = 2)
    @Valid
    protected List<Authorisation1Choice> authorisationChoices;
    @XmlElement(name = "NbOfTxs", required = true)
    @NotNull
    @Pattern(regexp = "[0-9]{1,15}")
    protected String transactionNumber;
    @XmlElement(name = "CtrlSum")
    @Digits(integer = 18, fraction = 17)
    protected BigDecimal ctrlSum;
    @XmlElement(name = "InitgPty", required = true)
    @NotNull
    @Valid
    protected PartyIdentification43 partyIdentification;
    @XmlElement(name = "FwdgAgt")
    @Valid
    protected BranchAndFinancialInstitutionIdentification5 branchAndFinancialInstitutionIdentification;

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDateTime(Date value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the authorisationChoices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorisationChoices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorisationChoices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Authorisation1Choice }
     * 
     * 
     */
    public List<Authorisation1Choice> getAuthorisationChoices() {
        if (authorisationChoices == null) {
            authorisationChoices = new ArrayList<Authorisation1Choice>();
        }
        return this.authorisationChoices;
    }

    /**
     * Gets the value of the transactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * Sets the value of the transactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionNumber(String value) {
        this.transactionNumber = value;
    }

    /**
     * Gets the value of the ctrlSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCtrlSum() {
        return ctrlSum;
    }

    /**
     * Sets the value of the ctrlSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCtrlSum(BigDecimal value) {
        this.ctrlSum = value;
    }

    /**
     * Gets the value of the partyIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification43 }
     *     
     */
    public PartyIdentification43 getPartyIdentification() {
        return partyIdentification;
    }

    /**
     * Sets the value of the partyIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification43 }
     *     
     */
    public void setPartyIdentification(PartyIdentification43 value) {
        this.partyIdentification = value;
    }

    /**
     * Gets the value of the branchAndFinancialInstitutionIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification5 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification5 getBranchAndFinancialInstitutionIdentification() {
        return branchAndFinancialInstitutionIdentification;
    }

    /**
     * Sets the value of the branchAndFinancialInstitutionIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification5 }
     *     
     */
    public void setBranchAndFinancialInstitutionIdentification(BranchAndFinancialInstitutionIdentification5 value) {
        this.branchAndFinancialInstitutionIdentification = value;
    }

    public void setAuthorisationChoices(List<Authorisation1Choice> value) {
        this.authorisationChoices = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = new JAXBToStringStrategy();
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theMessageId;
            theMessageId = this.getMessageId();
            strategy.appendField(locator, this, "messageId", buffer, theMessageId, (this.messageId!= null));
        }
        {
            Date theCreateDateTime;
            theCreateDateTime = this.getCreateDateTime();
            strategy.appendField(locator, this, "createDateTime", buffer, theCreateDateTime, (this.createDateTime!= null));
        }
        {
            List<Authorisation1Choice> theAuthorisationChoices;
            theAuthorisationChoices = (((this.authorisationChoices!= null)&&(!this.authorisationChoices.isEmpty()))?this.getAuthorisationChoices():null);
            strategy.appendField(locator, this, "authorisationChoices", buffer, theAuthorisationChoices, ((this.authorisationChoices!= null)&&(!this.authorisationChoices.isEmpty())));
        }
        {
            String theTransactionNumber;
            theTransactionNumber = this.getTransactionNumber();
            strategy.appendField(locator, this, "transactionNumber", buffer, theTransactionNumber, (this.transactionNumber!= null));
        }
        {
            BigDecimal theCtrlSum;
            theCtrlSum = this.getCtrlSum();
            strategy.appendField(locator, this, "ctrlSum", buffer, theCtrlSum, (this.ctrlSum!= null));
        }
        {
            PartyIdentification43 thePartyIdentification;
            thePartyIdentification = this.getPartyIdentification();
            strategy.appendField(locator, this, "partyIdentification", buffer, thePartyIdentification, (this.partyIdentification!= null));
        }
        {
            BranchAndFinancialInstitutionIdentification5 theBranchAndFinancialInstitutionIdentification;
            theBranchAndFinancialInstitutionIdentification = this.getBranchAndFinancialInstitutionIdentification();
            strategy.appendField(locator, this, "branchAndFinancialInstitutionIdentification", buffer, theBranchAndFinancialInstitutionIdentification, (this.branchAndFinancialInstitutionIdentification!= null));
        }
        return buffer;
    }

}
