//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:33:09 AM ICT 
//


package com.example.jaxb.domain.pain_002_001_07;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.example.jaxb.util.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CstmrPmtStsRpt" type="{urn:iso:std:iso:20022:tech:xsd:pain.002.001.07}CustomerPaymentStatusReportV07"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "customerPaymentStatusReport"
})
@XmlRootElement(name = "Document")
public class Document implements ToString2
{

    @XmlElement(name = "CstmrPmtStsRpt", required = true)
    @NotNull
    @Valid
    protected CustomerPaymentStatusReportV07 customerPaymentStatusReport;

    /**
     * Gets the value of the customerPaymentStatusReport property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPaymentStatusReportV07 }
     *     
     */
    public CustomerPaymentStatusReportV07 getCustomerPaymentStatusReport() {
        return customerPaymentStatusReport;
    }

    /**
     * Sets the value of the customerPaymentStatusReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPaymentStatusReportV07 }
     *     
     */
    public void setCustomerPaymentStatusReport(CustomerPaymentStatusReportV07 value) {
        this.customerPaymentStatusReport = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = new JAXBToStringStrategy();
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            CustomerPaymentStatusReportV07 theCustomerPaymentStatusReport;
            theCustomerPaymentStatusReport = this.getCustomerPaymentStatusReport();
            strategy.appendField(locator, this, "customerPaymentStatusReport", buffer, theCustomerPaymentStatusReport, (this.customerPaymentStatusReport!= null));
        }
        return buffer;
    }

}
